{
  "Severity": "MODERATE",
  "UpdatedAt": "2024-09-10T21:47:35Z",
  "Package": {
    "Ecosystem": "PIP",
    "Name": "ansible"
  },
  "Advisory": {
    "DatabaseId": 140800,
    "Id": "GSA_kwCzR0hTQS1oNjUzLTk1cXctaDJtcM4AAiYA",
    "GhsaId": "GHSA-h653-95qw-h2mp",
    "References": [
      {
        "Url": "https://nvd.nist.gov/vuln/detail/CVE-2019-14858"
      },
      {
        "Url": "https://github.com/ansible/ansible/pull/63405"
      },
      {
        "Url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14858"
      },
      {
        "Url": "https://github.com/ansible/ansible/commit/0fd656e9964a91f2e8b1e9bbf78c74661ab9d37b"
      },
      {
        "Url": "https://github.com/ansible/ansible/commit/3dfb8e81bb5f776a6b00c7a90dd087e85b71f8bb"
      },
      {
        "Url": "https://github.com/ansible/ansible/commit/87f8d77d70476454f7fe2381bd363a329ce4266c"
      },
      {
        "Url": "https://github.com/ansible/ansible/commit/f610ed3a4eb87eb557200606279796921fa9b722"
      },
      {
        "Url": "https://access.redhat.com/errata/RHSA-2019:3201"
      },
      {
        "Url": "https://access.redhat.com/errata/RHSA-2019:3202"
      },
      {
        "Url": "https://access.redhat.com/errata/RHSA-2019:3203"
      },
      {
        "Url": "https://access.redhat.com/errata/RHSA-2019:3207"
      },
      {
        "Url": "https://access.redhat.com/errata/RHSA-2020:0756"
      },
      {
        "Url": "https://github.com/pypa/advisory-database/tree/main/vulns/ansible/PYSEC-2019-171.yaml"
      },
      {
        "Url": "http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00021.html"
      },
      {
        "Url": "http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00026.html"
      },
      {
        "Url": "https://github.com/advisories/GHSA-h653-95qw-h2mp"
      }
    ],
    "Identifiers": [
      {
        "Type": "GHSA",
        "Value": "GHSA-h653-95qw-h2mp"
      },
      {
        "Type": "CVE",
        "Value": "CVE-2019-14858"
      }
    ],
    "Description": "A vulnerability was found in Ansible engine 2.x up to 2.8 and Ansible tower 3.x up to 3.5. When a module has an argument_spec with sub parameters marked as `no_log`, passing an invalid parameter name to the module will cause the task to fail before the `no_log` options in the sub parameters are processed. As a result, data in the sub parameter fields will not be masked and will be displayed if Ansible is run with increased verbosity and present in the module invocation arguments for the task.",
    "Origin": "UNSPECIFIED",
    "PublishedAt": "2022-05-24T16:58:43Z",
    "Severity": "MODERATE",
    "Summary": "Ansible leaks sensitive information to logs when told not to",
    "UpdatedAt": "2024-09-10T21:47:35Z",
    "WithdrawnAt": "",
    "CVSS": {
      "Score": 5.5,
      "VectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N"
    }
  },
  "Versions": [
    {
      "FirstPatchedVersion": {
        "Identifier": "2.6.20"
      },
      "VulnerableVersionRange": "\u003e= 2.0, \u003c 2.6.20"
    },
    {
      "FirstPatchedVersion": {
        "Identifier": "2.7.14"
      },
      "VulnerableVersionRange": "\u003e= 2.7.0a1, \u003c 2.7.14"
    },
    {
      "FirstPatchedVersion": {
        "Identifier": "2.8.6"
      },
      "VulnerableVersionRange": "\u003e= 2.8.0a1, \u003c 2.8.6"
    },
    {
      "FirstPatchedVersion": {
        "Identifier": "2.9.0rc4"
      },
      "VulnerableVersionRange": "\u003e= 2.9.0a1, \u003c 2.9.0rc4"
    }
  ]
}