{
  "Identifier": "CVE-2021-37668",
  "PackageSlug": "pypi/tensorflow",
  "Title": "FPE in `tf.raw_ops.UnravelIndex`",
  "Description": "An attacker can cause denial of service in applications serving models using `tf.raw_ops.UnravelIndex` by triggering a division by 0:\n\n```python\nimport tensorflow as tf\n\ntf.raw_ops.UnravelIndex(indices=-1, dims=[1,0,2])\n```",
  "Date": "2024-11-13",
  "Pubdate": "2021-08-25",
  "AffectedRange": "\u003c2.3.4||\u003e=2.4.0,\u003c2.4.3||\u003e=2.5.0,\u003c2.5.1||==2.5.0",
  "FixedVersions": [
    "2.3.4",
    "2.4.3",
    "2.5.1"
  ],
  "AffectedVersions": "All versions before 2.3.4, all versions starting from 2.4.0 before 2.4.3, all versions starting from 2.5.0 before 2.5.1, version 2.5.0",
  "NotImpacted": "",
  "Solution": "Upgrade to versions 2.3.4, 2.4.3, 2.5.1 or above.",
  "Urls": [
    "https://nvd.nist.gov/vuln/detail/CVE-2021-37668",
    "https://github.com/advisories/GHSA-2wmv-37vq-52g5",
    "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-2wmv-37vq-52g5",
    "https://github.com/tensorflow/tensorflow/commit/a776040a5e7ebf76eeb7eb923bf1ae417dd4d233",
    "https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-cpu/PYSEC-2021-581.yaml",
    "https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow-gpu/PYSEC-2021-779.yaml",
    "https://github.com/pypa/advisory-database/tree/main/vulns/tensorflow/PYSEC-2021-290.yaml",
    "https://github.com/tensorflow/tensorflow"
  ],
  "CvssV2": "AV:L/AC:L/Au:N/C:N/I:N/A:P",
  "CvssV3": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
  "UUID": "0d9849e1-07bc-4b7f-b920-3d54b4ca76c1"
}