{
  "Severity": "MODERATE",
  "UpdatedAt": "2019-12-02T01:15:53Z",
  "Package": {
    "Ecosystem": "PIP",
    "Name": "ecdsa"
  },
  "Advisory": {
    "DatabaseId": 1822,
    "Id": "MDE2OlNlY3VyaXR5QWR2aXNvcnlHSFNBLTJtcmotNDM1di1jMmNy",
    "GhsaId": "GHSA-2mrj-435v-c2cr",
    "References": [
      {
        "Url": "https://nvd.nist.gov/vuln/detail/CVE-2019-14853"
      },
      {
        "Url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14853"
      },
      {
        "Url": "https://github.com/warner/python-ecdsa/releases/tag/python-ecdsa-0.13.3"
      },
      {
        "Url": "https://seclists.org/bugtraq/2019/Dec/33"
      },
      {
        "Url": "https://www.debian.org/security/2019/dsa-4588"
      },
      {
        "Url": "https://github.com/advisories/GHSA-2mrj-435v-c2cr"
      }
    ],
    "Identifiers": [
      {
        "Type": "GHSA",
        "Value": "GHSA-2mrj-435v-c2cr"
      }
    ],
    "Description": "**Withdrawn:** Duplicate of GHSA-pwfw-mgfj-7g3g.",
    "Origin": "UNSPECIFIED",
    "PublishedAt": "2019-12-02T18:15:31Z",
    "Severity": "MODERATE",
    "Summary": "possible DoS caused by malformed signature decoding in Pure-Python ECDSA",
    "UpdatedAt": "2023-01-09T05:02:06Z",
    "WithdrawnAt": "2020-06-16T20:15:24Z",
    "CVSS": {
      "Score": 0,
      "VectorString": ""
    }
  },
  "Versions": [
    {
      "FirstPatchedVersion": {
        "Identifier": "0.13.3"
      },
      "VulnerableVersionRange": "\u003c 0.13.3"
    }
  ]
}