{
  "Title": "python-pymisp-doc-2.4.148-2.2 on GA media",
  "Tracking": {
    "ID": "openSUSE-SU-2024:11255-1",
    "Status": "Final",
    "Version": "1",
    "InitialReleaseDate": "2024-06-15T00:00:00Z",
    "CurrentReleaseDate": "2024-06-15T00:00:00Z",
    "RevisionHistory": [
      {
        "Number": "1",
        "Date": "2024-06-15T00:00:00Z",
        "Description": "current"
      }
    ]
  },
  "Notes": [
    {
      "Text": "python-pymisp-doc-2.4.148-2.2 on GA media",
      "Title": "Topic",
      "Type": "Summary"
    },
    {
      "Text": "These are all security issues fixed in the python-pymisp-doc-2.4.148-2.2 package on the GA media of openSUSE Tumbleweed.",
      "Title": "Details",
      "Type": "General"
    },
    {
      "Text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
      "Title": "Terms of Use",
      "Type": "Legal Disclaimer"
    },
    {
      "Text": "openSUSE-Tumbleweed-2024-11255",
      "Title": "Patchnames",
      "Type": "Details"
    }
  ],
  "ProductTree": {
    "Relationships": [
      {
        "ProductReference": "python-pymisp-doc-2.4.148-2.2",
        "RelatesToProductReference": "openSUSE Tumbleweed",
        "RelationType": "Default Component Of"
      },
      {
        "ProductReference": "python36-pymisp-2.4.148-2.2",
        "RelatesToProductReference": "openSUSE Tumbleweed",
        "RelationType": "Default Component Of"
      },
      {
        "ProductReference": "python38-pymisp-2.4.148-2.2",
        "RelatesToProductReference": "openSUSE Tumbleweed",
        "RelationType": "Default Component Of"
      },
      {
        "ProductReference": "python39-pymisp-2.4.148-2.2",
        "RelatesToProductReference": "openSUSE Tumbleweed",
        "RelationType": "Default Component Of"
      }
    ]
  },
  "References": [
    {
      "URL": "https://www.suse.com/support/security/rating/",
      "Description": "SUSE Security Ratings"
    },
    {
      "URL": "https://www.suse.com/security/cve/CVE-2019-11324/",
      "Description": "SUSE CVE CVE-2019-11324 page"
    }
  ],
  "Vulnerabilities": [
    {
      "CVE": "CVE-2019-11324",
      "Description": "The urllib3 library before 1.24.2 for Python mishandles certain cases where the desired set of CA certificates is different from the OS store of CA certificates, which results in SSL connections succeeding in situations where a verification failure is the correct outcome. This is related to use of the ssl_context, ca_certs, or ca_certs_dir argument.",
      "Threats": [
        {
          "Type": "Impact",
          "Severity": "low"
        }
      ],
      "References": [
        {
          "URL": "https://www.suse.com/security/cve/CVE-2019-11324.html",
          "Description": "CVE-2019-11324"
        },
        {
          "URL": "https://bugzilla.suse.com/1132900",
          "Description": "SUSE Bug 1132900"
        }
      ],
      "ProductStatuses": [
        {
          "Type": "Fixed",
          "ProductID": [
            "openSUSE Tumbleweed:python-pymisp-doc-2.4.148-2.2",
            "openSUSE Tumbleweed:python36-pymisp-2.4.148-2.2",
            "openSUSE Tumbleweed:python38-pymisp-2.4.148-2.2",
            "openSUSE Tumbleweed:python39-pymisp-2.4.148-2.2"
          ]
        }
      ],
      "CVSSScoreSets": {
        "BaseScore": "5",
        "Vector": "AV:N/AC:L/Au:N/C:N/I:P/A:N"
      }
    }
  ]
}