{
  "id": "MAL-2024-5593",
  "modified": "2024-10-24T01:01:59Z",
  "published": "2024-06-25T13:39:04Z",
  "aliases": [
    "SNYK-PYTHON-PYCOED-6513677"
  ],
  "summary": "Malicious code in py-coed (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "py-coed",
        "purl": "pkg:pypi/py-coed"
      },
      "versions": [
        "1.0.0"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/py-coed/MAL-2024-5593.json"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-PYCOED-6513677"
    },
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
    }
  ]
}