{
  "Identifier": "CVE-2013-4188",
  "PackageSlug": "pypi/Plone",
  "Title": "Plone Authenticated Denial of Service vulnerability",
  "Description": "traverser.py in Plone 2.1 through 4.1, 4.2.x through 4.2.5, and 4.3.x through 4.3.1 allows remote attackers with administrator privileges to cause a denial of service (infinite loop and resource consumption) via unspecified vectors related to \"retrieving information for certain resources.\"",
  "Date": "2023-08-29",
  "Pubdate": "2022-05-17",
  "AffectedRange": "\u003e=2.1,\u003c=4.2.6||\u003e=4.3,\u003c4.3.2",
  "FixedVersions": [
    "4.3.2"
  ],
  "AffectedVersions": "All versions starting from 2.1 up to 4.2.6, all versions starting from 4.3 before 4.3.2",
  "NotImpacted": "All versions before 2.1, all versions after 4.2.6 before 4.3, all versions starting from 4.3.2",
  "Solution": "Upgrade to version 4.3.2 or above.",
  "Urls": [
    "https://nvd.nist.gov/vuln/detail/CVE-2013-4188",
    "https://bugzilla.redhat.com/show_bug.cgi?id=978449",
    "http://plone.org/products/plone-hotfix/releases/20130618",
    "http://plone.org/products/plone/security/advisories/20130618-announcement",
    "http://seclists.org/oss-sec/2013/q3/261",
    "https://github.com/advisories/GHSA-w3pw-qxjj-6prr"
  ],
  "CvssV2": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
  "CvssV3": "",
  "UUID": "d274f890-bb85-4b34-9643-270c67407ebc"
}