{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "children": [],
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:a:libpod_project:libpod:1.6.0:-:*:*:*:*:*:*",
            "cpe_name": [],
            "vulnerable": true
          }
        ],
        "operator": "OR"
      },
      {
        "children": [],
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:o:redhat:enterprise_linux:8.0:*:*:*:*:*:*:*",
            "cpe_name": [],
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:redhat:openshift_container_platform:4.3:*:*:*:*:*:*:*",
            "cpe_name": [],
            "vulnerable": true
          }
        ],
        "operator": "OR"
      }
    ]
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "secalert@redhat.com",
      "ID": "CVE-2020-1726"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "A flaw was discovered in Podman where it incorrectly allows containers when created to overwrite existing files in volumes, even if they are mounted as read-only. When a user runs a malicious container or a container based on a malicious image with an attached volume that is used for the first time, it is possible to trigger the flaw and overwrite files in the volume.This issue was introduced in version 1.6.0."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-552"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1726",
          "refsource": "CONFIRM",
          "tags": [
            "Issue Tracking",
            "Patch",
            "Third Party Advisory"
          ],
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1726"
        },
        {
          "name": "RHSA-2020:0680",
          "refsource": "REDHAT",
          "tags": [],
          "url": "https://access.redhat.com/errata/RHSA-2020:0680"
        },
        {
          "name": "openSUSE-SU-2020:1552",
          "refsource": "SUSE",
          "tags": [],
          "url": "http://lists.opensuse.org/opensuse-security-announce/2020-09/msg00097.html"
        },
        {
          "name": "openSUSE-SU-2020:1559",
          "refsource": "SUSE",
          "tags": [],
          "url": "http://lists.opensuse.org/opensuse-security-announce/2020-09/msg00103.html"
        }
      ]
    }
  },
  "impact": {
    "baseMetricV2": {
      "acInsufInfo": false,
      "cvssV2": {
        "accessComplexity": "MEDIUM",
        "accessVector": "NETWORK",
        "authentication": "NONE",
        "availabilityImpact": "PARTIAL",
        "baseScore": 5.8,
        "confidentialityImpact": "NONE",
        "integrityImpact": "PARTIAL",
        "vectorString": "AV:N/AC:M/Au:N/C:N/I:P/A:P",
        "version": "2.0"
      },
      "exploitabilityScore": 8.6,
      "impactScore": 4.9,
      "obtainAllPrivilege": false,
      "obtainOtherPrivilege": false,
      "obtainUserPrivilege": false,
      "severity": "MEDIUM",
      "userInteractionRequired": false
    },
    "baseMetricV3": {
      "cvssV3": {
        "attackComplexity": "HIGH",
        "attackVector": "NETWORK",
        "availabilityImpact": "NONE",
        "baseScore": 5.9,
        "baseSeverity": "MEDIUM",
        "confidentialityImpact": "NONE",
        "integrityImpact": "HIGH",
        "privilegesRequired": "NONE",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:H/A:N",
        "version": "3.1"
      },
      "exploitabilityScore": 2.2,
      "impactScore": 3.6
    }
  },
  "lastModifiedDate": "2023-02-12T23:40Z",
  "publishedDate": "2020-02-11T20:15Z"
}