{
  "id": "MAL-2025-47797",
  "modified": "2025-09-26T09:14:29Z",
  "published": "2025-09-26T09:14:29Z",
  "summary": "Malicious code in python-dateitil (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "python-dateitil",
        "purl": "pkg:pypi/python-dateitil"
      },
      "versions": [
        "0.1.2"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/python-dateitil/MAL-2025-47797.json"
      }
    }
  ]
}