{
  "id": "MAL-2023-8651",
  "modified": "2023-12-12T00:33:23Z",
  "published": "2023-12-01T21:54:02Z",
  "withdrawn": "2023-12-12T00:33:23Z",
  "summary": "Malicious code in lodestone (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n\n## Source: ossf-package-analysis (c5569d9f5d17acc6330446faa4b9f8eff7b389a4cde9698946b8473c5bd8e74e)\nThe OpenSSF Package Analysis project identified 'lodestone' @ 0.0.58 (pypi) as malicious.\n\nIt is considered malicious because:\n\n- The package communicates with a domain associated with malicious activity.\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "lodestone",
        "purl": "pkg:pypi/lodestone"
      },
      "versions": [
        "0.0.58",
        "0.0.59",
        "0.0.62",
        "0.0.63"
      ],
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/withdrawn/pypi/lodestone/MAL-2023-8651.json"
      }
    }
  ]
}